app = "app-rzyqrlgu"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  MAX_WORKERS = "1"
  TORCH_THREADS = "1"
  TOKENIZERS_PARALLELISM = "false"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "2048mb"
  cpu_kind = "shared"
  cpus = 1
